version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini  # คัดลอกไฟล์ php.ini หากมี
    networks:
      - laravel-network
    depends_on:
      - mysql
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8080:80"  # ใช้ port 8080 สำหรับการเข้าถึงเว็บไซต์
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # กำหนด config ของ Nginx
    networks:
      - laravel-network
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: laraveluser
      PMA_PASSWORD: laravelpass
    depends_on:
      - mysql
    networks:
      - laravel-network

volumes:
  mysql_data:

networks:
  laravel-network:
